caam_email_sender=PSM_Cyber-Ark@voya.com
#caam_email_recepients=Srikanth.Kamarthy@voya.com,Sergio.Bascon@voya.com,Susmita.Das@voya.com,VigneshKumar.V@voya.com
caam_email_recepients=Sergio.Bascon@voya.com
#caam_email_recepients=SHR-US-TOOLS@voya.com,pamengineering@voya.com
#files_drive=D:/
files_drive=C:/
log_files_path=CAAM-Logs/log-Transcripts
input_files_path=CAAM-InputFiles
input_methods=manual,bulk
default_input_method=manual