dap_write_prod_url=https://dap-write.apptoapp.net
dap_write_accp_url=https://dap-write.accp.apptoapp.net
dap_read_prod_url=https://dap-read.apptoapp.net
dap_read_accp_url=https://dap-read.accp.apptoapp.net
dap_dev_url=https://dap-dev.dsglobal.org
dap_prod_account=prod
dap_accp_account=accp
dap_dev_account=sandbox
dap_policy_output_path=/CAAM-InputFiles/dap-Policies
