Windows=2_W_PWD_MNL
Windows1=3_W_PWD_MNL
Windows2=4_W_PWD_MNL
Linux=2_U_PWD_MNL
SQL=2_DQ_PWD_MNL_DAP
Oracle=2_DO_PWD_MNL_DAP
Sybase=2_DS_PWD_MNL_DAP
Mainframe=2_M_PWD_MNL_DAP
DB2=2_U_PWD_MNL_DAP
Application=2_AP_PWD_MNL_DAP
APIKey= 2_AP_KEY_MNL_DAP 