PLT01=2_W_PWD_MNL
PLT02=3_W_PWD_MNL
PLT03=4_W_PWD_MNL
PLT04=2_U_PWD_MNL
PLT05=2_DQ_PWD_MNL_DAP
PLT06=2_DO_PWD_MNL_DAP
PLT07=2_DS_PWD_MNL_DAP
PLT08=2_M_PWD_MNL_DAP
PLT09=2_U_PWD_MNL_DAP
PLT10=2_AP_PWD_MNL_DAP
PLT11= 2_AP_KEY_MNL_DAP 
PLT12=2_AP_PWD_MNL_DAP
PLT13= 2_AP_KEY_MNL_DAP 
PLT14=2_AP_PWD_MNL_DAP
PLT15= 2_AP_KEY_MNL_DAP 