PLT01=LinuxSSH20 Hours_DC
PLT02=LinuxSSH20 Hours_EA
PLT03=LinuxSSH20 Hours_EA_RR
PLT04=LinuxSSH20 Hours_RR
PLT05=LinuxSSH20Hours
PLT06=LinuxSSH20Hours_DC
PLT07=LinuxSSH20Hours_DC_EA
PLT08=LinuxSSH20Hours_RR
PLT09=Static-UNIX-Linux-SSH
PLT10=Static-UNIX-Linux-SSH_DC
PLT11=PROD-SSH-RR-DC-SC
PLT12=PROD-SSH-RR-DC-SC-AutoLogin
PLT13=PROD-SSH-RR-DC-SC-Autologin 