PLT01=LinuxSSH20 Hours_EA
PLT02=LinuxSSH20 Hours_EA_RR
PLT03=LinuxSSH20 Hours_RR
PLT04=LinuxSSH20Hours
PLT05=LinuxSSH20Hours_RR
PLT06=Static-UNIX-Linux-SSH
PLT07=NONPROD-ROOT-SSH-RR-SC
PLT08=NONPROD-SSH-RR
PLT09=NONPROD-SSH-RR-Autologin
PLT10=NONPROD-SSH-SES-RR-Autologin