PLT01=LinuxSSH20Hours
PLT02=MSSql20Hours
PLT03=Oracle20Hours
PLT04=OS390SSH20Hours
PLT05=Sybase20Hours
PLT06=Windows20Hours
PLT07=WindowsPersonal20Hours
PLT08=WindowsPersonal4Days
PLT09=WindowsPersonal8Days